### PR TITLE
Backward Euler for sesolve

### PR DESCRIPTION
**Pull request by pierreguilmin**
Too easy to ignore it. The backward Euler method: 1st order, fixed step size, implicit.

### CODE REVIEW

**Review by abocquet — COMMENTED** [review]
Great job going for low hanging fruit! I'm wondering whether `BEuler` is the best name though 🤔 Would `ImplicitEuler` be more explicit (no pun intended)? `BackwardEuler` works too but is a bit confusing as I originally thought it was the backward autodiff with Euler

**Comment by pierreguilmin** [comment]
> Great job going for low hanging fruit! I'm wondering whether `BEuler` is the best name though 🤔 Would `ImplicitEuler` be more explicit (no pun intended)? `BackwardEuler` works too but is a bit confusing as I originally thought it was the backward autodiff with Euler

Right, I don't have a clear opinion on this, I'm fine with `ImplicitEuler` too, wdyt @gautierronan?

**Comment by gautierronan** [comment]
> Right, I don't have a clear opinion on this, I'm fine with `ImplicitEuler` too, wdyt @gautierronan?

"Backward Euler" is the true name of the method. So I think we should keep it like this, and make it clear that it's implicit in the documentation.

**Review by gautierronan — APPROVED** [review]
LGTM

**Review by abocquet — APPROVED** [review]

**Pull request merged**
