### PR TITLE
Implement differentiable inv matrix square root

### PR DESCRIPTION
**Pull request by abocquet**
Use a new version of matrix inverse square root, based on https://arxiv.org/abs/2201.08663

It enables auto differentiation and is faster.

Rapid benchmark on a RTX4090
image

Solves #237

### CODE REVIEW

**Review by gautierronan — APPROVED** [review]
Very nice ! No need for a proper test, but did you check that it computes the right sqrtm in forward and in backward? If so, I think we can merge.

**Comment by abocquet** [comment]
There is a test in Rouchon that ensures the forward and backward pass work correclty. I tried to mess with the code and it crashed so it must be OK

**Review by pierreguilmin — CHANGES_REQUESTED** [review]
I think there is a bug
```python
>>> import torch
>>> from dynamiqs.solvers.utils.utils import inv_sqrtm
>>> n = 4
>>> x = torch.rand((n, n))
>>> xm12 = inv_sqrtm(x)
>>> torch.allclose(x @ xm12 @ xm12, torch.eye(n), rtol=1e-3, atol=1e-3)
False
>>> x @ xm12 @ xm12
tensor([[[ 0.7475,  1.8410, -0.9934, -1.5469],
         [ 0.2476, -0.2559,  0.6473,  0.9988],
         [-0.3816,  1.1147,  0.6527, -1.0096],
         [ 0.1111, -0.7517,  0.3074,  1.7687]]])
```

We should write unit tests for this logic, it's a bit too technical to trust it.

**Comment by pierreguilmin** [comment]
Should we close this @abocquet?

**Pull request closed without merging**
