### PR TITLE
Add extra args to callable Hamiltonians

### PR DESCRIPTION
**Pull request by gautierronan**
Small PR to add Hamiltonians of the form `H(t: float, *args) -> Tensor` instead of `H(t: float) -> Tensor`.

- [ ] Test it works with an example.
- [ ] Write a test function ?

### CODE REVIEW

**Comment by pierreguilmin** [comment]
I don't see the use case for this 🤔 If you know the `*args` when you define `options`, then you can easily define a `H` function compatible with `dynamiqs`:
```python
H = lambda t: H_with_args(t, *args)
```

**Comment by gautierronan** [comment]
> I don't see the use case for this 🤔 If you know the `*args` when you define `options`, then you can easily define a `H` function compatible with `dynamiqs`:
> 
> ```python
> H = lambda t: H_with_args(t, *args)
> ```

Don't know enough about the good coding practices, but isn't it considered a bad habit to do what you describe? Doesn't this make `*args` a hidden/global variable or something like that?

For instance [`scipy.optimize.minimize`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.minimize.html) does what I implemented in this PR, and so does QuTiP.

**Comment by pierreguilmin** [comment]
> Don't know enough about the good coding practices, but isn't it considered a bad habit to do what you describe? Doesn't this make `*args` a hidden/global variable or something like that?

Not that I know of, it's actually better IMO. But maybe @abocquet has a different opinion on this? I think scipy and qutip do this for convenience (so you don't have to define a lambda function to match their API), but I find it rather confusing to mix my personal function arguments with the minimizer/solver options 🤷‍♂️

**Comment by gautierronan** [comment]
> > Don't know enough about the good coding practices, but isn't it considered a bad habit to do what you describe? Doesn't this make `*args` a hidden/global variable or something like that?
> 
> Not that I know of, it's actually better IMO. But maybe @abocquet has a different opinion on this? I think scipy and qutip do this for convenience (so you don't have to define a lambda function to match their API), but I find it rather confusing to mix my personal function arguments with the minimizer/solver options 🤷‍♂️

Ok I'm fine with either solution. This PR is definitly short enough that I don't care whether it's pushed or not :D

**Comment by pierreguilmin** [comment]
Closing this as discussed, don't hesitate to reopen if you disagree.

**Pull request closed without merging**
