### PR TITLE
Add progress bar

### PR DESCRIPTION
**Pull request by abocquet**
Adds progress bar options once https://github.com/patrick-kidger/diffrax/pull/357 is merged

### CODE REVIEW

**Review by gautierronan — APPROVED** [review]
Nice !

**Comment by gautierronan** [comment]
Just thinking: should we check for the diffrax version until the diffrax.progress_meter is actually released?

**Comment by pierreguilmin** [comment]
@abocquet I'm closing this while waiting for the various fixes and integration in Diffrax. 😊 (or we can reopen and make it draft if you prefer)

**Comment by gautierronan** [comment]
Reopening as draft to show that this is still WIP. We're mostly waiting for the next release of diffrax to propagate the changes.

**Review by gautierronan — APPROVED** [review]
:rocket:

**Pull request merged**
