### PR TITLE
Introduce global settings file

### PR DESCRIPTION
**Pull request by gautierronan**
This PR makes a few different changes to the `jax_utils.py` file:

1. Renames it into `global_settings.py`
2. Moves `set_layout` into this file instead of `qarray/utils.py`
3. Changes the API of `set_layout` from `set_layout(layout: Layout)` to `set_layout(layout: Literal['dense', 'dia'])` to mimic other functions in the file
4. Moves the `to_qutip` utility to a method of the QArray class only, similar to the `to_jax` method (mostly because it was a standalone function for now).

Can review commit by commit.

### CODE REVIEW

**Comment by pierreguilmin** [comment]
Great, here are a few minor commits on top.

The only thing I disagree with is
> Moves the `to_qutip` utility to a method of the QArray class only, similar to the to_jax method (mostly because it was a standalone function for now).

This utility is very useful for people working with simple jax Arrays too, I think we should add it back.

**Comment by gautierronan** [comment]
> This utility is very useful for people working with simple jax Arrays too, I think we should add it back.

No problem adding it back, but it should not be within the "Global Settings" section (and I quite like having this). We could put it within "QArray utilities" together with `dq.stack` ?

**Comment by gautierronan** [comment]
Should be good @pierreguilmin

**Review by pierreguilmin — APPROVED** [review]
Molto bene

**Pull request merged**
