### PR TITLE
Add `dq.proj()`

### PR DESCRIPTION
**Pull request by lucasoeth**
Form the projector from a given ket or bra vector.

Closes https://linear.app/dynamiqs/issue/DYN-37/add-proj.

### CODE REVIEW

**Comment by pierreguilmin** [comment]
Hey @lucasoeth, thanks a lot for your first contribution! There is a small mistake (you compute matrix tranpose instead of matrix adjoint). I've fixed it and done some minor cleanup in the following commits.

**Review by gautierronan — DISMISSED** [review]
LGTM

**Comment by lucasoeth** [comment]
is tests/test_plots.py:47:20: UP032 Use f-string instead of `format` call kept on purpose?

Thanks for reviewing my first commit. To many more :)

**Comment by pierreguilmin** [comment]
> is tests/test_plots.py:47:20: UP032 Use f-string instead of format call kept on purpose?

Nope, I guess due to the recent ruff update, let me fix it quickly.

**Review by pierreguilmin — APPROVED** [review]

**Pull request merged**
