### PR TITLE
Add `sepropagator` solver 

### PR DESCRIPTION
**Pull request by dkweiss31**
follow up to https://github.com/dynamiqs/dynamiqs/pull/629 after the api restructuring

Note that I slightly deviated from the suggested implementation. I did not feel it was necessary to implement the classes `SEPropagatorEulerIntegrator, SEPropagatorDopri5Integrator,...` because it is `sesolve` that is actually doing the integration. From a class inheritance perspective, there is no reason why `SEPropagatorDiffraxIntegrator` (which maybe we do want to rename to `SEPropagatorDynamiqsIntegrator`?) should inherit from `DiffraxIntegrator`, since `SEPropagatorDiffraxIntegrator` will not be implementing a `terms` method. Very happy to reconsider this decision if people feel strongly :).

### CODE REVIEW

**Review by gautierronan — APPROVED** [review]
Hi @dkweiss31. Thanks again for the PR.

I've added a bunch of commits to add checks, conversions, the automatic JIT, rename the integrator, and other minor things. I'll let you check that I didn't introduce any bug (but the tests still pass).

On my end, I'm good to merge. I'll let @pierreguilmin add his review.

**Comment by dkweiss31** [comment]
Thanks for those commits @gautierronan ! Just looked over your changes and everything LGTM :)

**Review by pierreguilmin — COMMENTED** [review]
Amazing work @dkweiss31 thanks a lot!! 🥳 I've added a bunch of minor fixes on top, mostly documentation/style related. Don't hesitate to discuss if you're not happy with one of the proposeed changes. I'm not done yet, I'll finish the review / minor edits tomorrow or this weekend. Left to review:
- [ ]  dynamiqs/integrators/core/expm_integrator.py
- [ ]  tests/propagator/test_propagator.py

**Comment by pierreguilmin** [comment]
Documentation looks like:
Screenshot 2024-07-25 at 11 56 30

**Comment by pierreguilmin** [comment]
@abocquet if you have time to quickly skim through the code that would be great, just in case you have other ideas. 😊

**Comment by pierreguilmin** [comment]
Also, I think it would be much better to just copy-paste the `sesolve/diffrax_integrator.py` as a new `sepropagator/diffrax_integrator.py`, and so replacing the `SEPropagatorDynamiqsIntegrator` by a bunch of `SEPropagatorDiffraxIntegrator`. The advantages are:
- decoupling the solver > nice bc it simplifies the architecture and dependencies (for example if we introduce a bug in `sesolve` it doesn't break the other solvers)
- avoid the hacky call to `_sesolve`
- avoid refactoring the internal `_sesolve` to support matrices as initial states

I'll do this change if you agree @gautierronan and @dkweiss31.

**Comment by pierreguilmin** [comment]
I broke the tests but they pass locally, I'm not sure what's going wrong on the ci. 🤔
```
tests/sepropagator/test_sepropagator.py:18: in <module>
    from ..solver_tester import SolverTester
E   ModuleNotFoundError: No module named 'tests.solver_tester'
```

**Comment by dkweiss31** [comment]
Thank you @pierreguilmin !! All of your fixes look great. I think the tests should pass with this latest commit, just needed solver -> integrator :)

**Comment by dkweiss31** [comment]
> Also, I think it would be much better to just copy-paste the `sesolve/diffrax_integrator.py` as a new `sepropagator/diffrax_integrator.py`, and so replacing the `SEPropagatorDynamiqsIntegrator` by a bunch of `SEPropagatorDiffraxIntegrator`. The advantages are:
> 
> * decoupling the solver > nice bc it simplifies the architecture and dependencies (for example if we introduce a bug in `sesolve` it doesn't break the other solvers)
> * avoid the hacky call to `_sesolve`
> * avoid refactoring the internal `_sesolve` to support matrices as initial states
> 
> I'll do this change if you agree @gautierronan and @dkweiss31.

I think I like this idea! I agree that the call to `_sesolve` is suboptimal, and this proposed implementation of `sepropagator` treats e.g. `sesolve` and `sepropagator` on equal footing as solvers (sorry, integrators!), whereas in my implementation `sesolve` was the true solver and `sepropagator` was just a wrapper (I guess I'm just restating your first point lol). I liked that prior implementation just because it was simple and took advantage of existing functionality, but the matrix-matrix vs. matrix-vector issue made that untenable. Happy for this change to be made!

**Comment by dkweiss31** [comment]
I've started on consolidating all of the expm methods, related to https://linear.app/dynamiqs/issue/DYN-202/batch-compute-the-propagator . I've started it on a new branch since I wasn't positive if we wanted to do this here, if you're interested please see https://github.com/dkweiss31/dynamiqs/tree/propagator_expm_consolidation. The `ExpmSolver` class now is used for all of `sesolve`, `sepropagator`, `mesolve` if the user specifies their solver as `Expm`.

**Comment by pierreguilmin** [comment]
> I've started on consolidating all of the expm methods, related to https://linear.app/dynamiqs/issue/DYN-202/batch-compute-the-propagator . I've started it on a new branch since I wasn't positive if we wanted to do this here, if you're interested please see https://github.com/dkweiss31/dynamiqs/tree/propagator_expm_consolidation. The `ExpmSolver` class now is used for all of `sesolve`, `sepropagator`, `mesolve` if the user specifies their solver as `Expm`.

That's great! I guess you're also solving [DYN-47](https://linear.app/dynamiqs/issue/DYN-47) as well with this branch then? Yes you were right to start a new branch, this PR is already quite a big change. I agree with renaming the `Propagator` solver for `sesolve`/`mesolve` to `Expm` which is more explicit.

To keep in mind for this next PR or another: we also need the option to choose between batch-computing the propagator (when memory is not an issue) versus iteratively computing it (when memory is an issue).

**Comment by gautierronan** [comment]
> Also, I think it would be much better to just copy-paste the `sesolve/diffrax_integrator.py` as a new `sepropagator/diffrax_integrator.py`, and so replacing the `SEPropagatorDynamiqsIntegrator` by a bunch of `SEPropagatorDiffraxIntegrator`. The advantages are:
> 
>   * decoupling the solver > nice bc it simplifies the architecture and dependencies (for example if we introduce a bug in `sesolve` it doesn't break the other solvers)
> 
>   * avoid the hacky call to `_sesolve`
> 
>   * avoid refactoring the internal `_sesolve` to support matrices as initial states
> 
> 
> I'll do this change if you agree @gautierronan and @dkweiss31.

Do you want to do this here or in another PR?

> Amazing work @dkweiss31 thanks a lot!! 🥳 I've added a bunch of minor fixes on top, mostly documentation/style related. Don't hesitate to discuss if you're not happy with one of the proposeed changes. I'm not done yet, I'll finish the review / minor edits tomorrow or this weekend. Left to review:
> 
>   * [ ]   dynamiqs/integrators/core/expm_integrator.py
> 
>   * [ ]   tests/propagator/test_propagator.py

Same, is this ok or you still want to review these two files?

If not for both of these questions, then I guess we can merge and take care of other topics in separate PRs.

**Review by pierreguilmin — APPROVED** [review]
Yes let's merge this one, congrats @dkweiss31 🥳

**Pull request merged**
