### PR TITLE
Add method to get bloch sphere coordinates of a ket or a density matrix

### PR DESCRIPTION
**Pull request by vaicecaze**
Implemented a method to get bloch sphere coordinates of a ket or a density matrix

### CODE REVIEW

**Review by pierreguilmin — CHANGES_REQUESTED** [review]
Nice!

As you can see the commits from your old PR are also included in this one. To keep only the last two commits you should:
1. Pull the latest version of `main`.
2. Rebase on top `git rebase --onto main HEAD~2`.
3. Force push the branch.

To begin with the review, we're missing one of the spherical coordinates: the radius. It will be one for a ket (if normalized), but $\leq1$ for a density matrix. For example `0.5 * (dq.fock_dm(2, 0) + dq.fock_dm(2, 1))` should be at the center of the sphere (`r=0`).

**Review by pierreguilmin — CHANGES_REQUESTED** [review]
Nice start! Could we:
- [x] rename the method to `bloch_coordinates`
- [x] order it before `wigner` in all the places where we list quantum utils

**Review by pierreguilmin — APPROVED** [review]
Great work @vaicecaze! I've enriched a bit the documentation and shuffled the code around, but not much changed. Ready to ship once approved by @gautierronan.

As for #738, we need to make another PR on top of this one to support vectorized inputs. 😉

**Review by gautierronan — APPROVED** [review]
Lovely! Congratulations and thank you @vaicecaze for your (first?) contribution :)

**Pull request merged**
