### PR TITLE
Implement sums of TimeArrays

### PR DESCRIPTION
**Pull request by gautierronan**
On top of https://github.com/dynamiqs/dynamiqs/pull/476.

This implements arbitrary sums of `TimeArrays` with IMO a pretty neat structure, i.e. a list an `eqx.Module` which takes a list of TimeArrays. 

Quick test that this works:
```python
from __future__ import annotations

import jax.numpy as jnp

import dynamiqs as dq

psi = dq.basis(2, 0)
tsave = jnp.linspace(0, 1.0, 100)

# array to batch over, and base value for unbatched
omegas = jnp.linspace(-1.0, 1.0, 20)
omega = 1.0

# === base functions
def Hx(t, omega):
    return jnp.cos(t * jnp.expand_dims(omega, (-1, -2))) * dq.sigmax()

def cx(t, omega):
    return jnp.cos(t * omega)

# === make various time arrays
H0 = dq.totime(lambda t: Hx(t, omega)) # unbatched callable
H1 = dq.totime((lambda t: cx(t, omega), dq.sigmax())) # unbatched modulated
H2 = dq.totime(Hx, omegas) # batched callable
H3 = dq.totime((cx, dq.sigmax()), omegas) # batched callable

# === test all unbatched pairs
print("=== unbatched")
print(dq.sesolve(H0, psi, tsave))
print(dq.sesolve(H1, psi, tsave))
print(dq.sesolve(H0+H0, psi, tsave))
print(dq.sesolve(H0+H1, psi, tsave))
print(dq.sesolve(H1+H1, psi, tsave))

# === test all batched pairs
print("=== batched")
print(dq.sesolve(H2, psi, tsave))
print(dq.sesolve(H3, psi, tsave))
print(dq.sesolve(H0+H2, psi, tsave))
print(dq.sesolve(H0+H3, psi, tsave))
print(dq.sesolve(H1+H2, psi, tsave))
print(dq.sesolve(H1+H3, psi, tsave))
print(dq.sesolve(H2+H2, psi, tsave))
print(dq.sesolve(H2+H3, psi, tsave))
print(dq.sesolve(H3+H3, psi, tsave))
```
```
=== unbatched
==== Result ====
Solver  : Tsit5
States  : Array complex64 (100, 2, 1) | 1.56 Kb
==== Result ====
Solver  : Tsit5
States  : Array complex64 (100, 2, 1) | 1.56 Kb
==== Result ====
Solver  : Tsit5
States  : Array complex64 (100, 2, 1) | 1.56 Kb
==== Result ====
Solver  : Tsit5
States  : Array complex64 (100, 2, 1) | 1.56 Kb
==== Result ====
Solver  : Tsit5
States  : Array complex64 (100, 2, 1) | 1.56 Kb
=== batched
==== Result ====
Solver  : Tsit5
States  : Array complex64 (20, 100, 2, 1) | 31.25 Kb
==== Result ====
Solver  : Tsit5
States  : Array complex64 (20, 100, 2, 1) | 31.25 Kb
==== Result ====
Solver  : Tsit5
States  : Array complex64 (20, 100, 2, 1) | 31.25 Kb
==== Result ====
Solver  : Tsit5
States  : Array complex64 (20, 100, 2, 1) | 31.25 Kb
==== Result ====
Solver  : Tsit5
States  : Array complex64 (20, 100, 2, 1) | 31.25 Kb
==== Result ====
Solver  : Tsit5
States  : Array complex64 (20, 100, 2, 1) | 31.25 Kb
==== Result ====
Solver  : Tsit5
States  : Array complex64 (20, 100, 2, 1) | 31.25 Kb
==== Result ====
Solver  : Tsit5
States  : Array complex64 (20, 100, 2, 1) | 31.25 Kb
==== Result ====
Solver  : Tsit5
States  : Array complex64 (20, 100, 2, 1) | 31.25 Kb
```

### CODE REVIEW

**Review by abocquet — CHANGES_REQUESTED** [review]
Great work! 

I am not convinced this is a neat construction. It goes against the functional approach we took until now. You require capturing variables before doing operation and this is the kind of things we usually don't do. Typically with very large matrices I think we will have the slow compilation time issue.
Also every time you change your arguments (here omega) it's not clear if you will have to re-jit or not.

I would be in favor of passing all dynamical arguments as a pytree to mesolve/sesolve and pass them to the functions at runtime. It's more in the functionnal vein of JAX and will prevent the potential long re-JIT-ing issues

**Comment by gautierronan** [comment]
> I am not convinced this is a neat construction. It goes against the functional approach we took until now. You require capturing variables before doing operation and this is the kind of things we usually don't do. Typically with very large matrices I think we will have the slow compilation time issue. Also every time you change your arguments (here omega) it's not clear if you will have to re-jit or not.
> 
> I acknowledge there is a great effort on the ergonomics but capturing variables is a pattern that we should really avoid.
> 
> I would be in favor of passing all dynamical arguments as a pytree to mesolve/sesolve and pass them to the functions at runtime. It's more in the functionnal vein of JAX and will prevent the potential long re-JIT-ing issues

So, I agree there could be better approaches to this problem. But I have been working on this/thinking about this for days, and TBH this is the neatest I could do. So feel free to propose another approach, but I personally don't have the time nor the will to re-do this once more.

That being said, I would be in favor of merging this by next week so we at least have a solution for our TimeArrays and that there's no breaking bug remaining. But I'd be happy to review and accept another refactorization of these TimeArrays afterwards.

**Comment by abocquet** [comment]
I propose that we do not merge this one and when all of you other PRs are merged I give it a try if that works for you

**Review by abocquet — APPROVED** [review]
Let's fix it later

**Review by pierreguilmin — APPROVED** [review]

**Pull request merged**
