### PR TITLE
Generalize dq.fock and dq.coherent to allow for batching and multi-mode initialization

### PR DESCRIPTION
**Pull request by gautierronan**
Closes DYN-208.

### CODE REVIEW

**Comment by pierreguilmin** [comment]
Very cool! I've added a bunch of commits on top to (i) improve and lighten the documentation, (ii) simplify the logic to check shapes and (iii) use a vectorized call to simplify the logic of `dq.fock()`.

**Review by pierreguilmin — APPROVED** [review]

**Comment by pierreguilmin** [comment]
@gautierronan waiting for your approval with the proposed modifications before merging. 😉

**Comment by gautierronan** [comment]
> @gautierronan waiting for your approval with the proposed modifications before merging. 😉

Made small modifications to the documentation on top, to try to make it a bit clearer. Let me know if that's ok with you.

**Comment by pierreguilmin** [comment]
@gautierronan great work!! 👏  I'm merging this. Do you think we should use density matrices notation e.g. $\ket0\bra0$ for the doc of `dq.fock_dm` and `dq.coherent_dm`?

**Review by pierreguilmin — APPROVED** [review]

**Pull request merged**
