### PR TITLE
Fix imageio "fps" deprecation warning.

### PR DESCRIPTION
**Pull request by gautierronan**
In older versions, the `fps` keyword is deprecated, which raises a bug when running `dq.plot_wigner_gif`.

Closes https://linear.app/dynamiqs/issue/DYN-175/fix-fps-warning-when-running-tests.

### CODE REVIEW

**Review by pierreguilmin — APPROVED** [review]
Thanks 🙏

**Comment by pierreguilmin** [comment]
Arf, actually it doesn't work:
```
→ pip list | grep imageio
imageio                    2.33.1
→ pytest dynamiqs/plots/plots_wigner.py
Test session starts (platform: darwin, Python 3.9.9, pytest 7.4.4, pytest-sugar 1.0.0)
rootdir: /Users/pierreguilmin/dev/github/dynamiqs
configfile: pytest.ini
plugins: jaxtyping-0.2.25, sugar-1.0.0, typeguard-2.13.3, xdist-3.5.0
collected 47 items

 dynamiqs/plots/plots_wigner.py ✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓       100% ██████████
========================================= warnings summary ==========================================
dynamiqs/plots/plots_wigner.py::line:276,column:1
dynamiqs/plots/plots_wigner.py::line:294,column:1
  /Users/pierreguilmin/.pyenv/versions/3.9.9/envs/dynamiqs/lib/python3.9/site-packages/imageio/plugins/pillow.py:409: DeprecationWarning: The keyword `fps` is no longer supported. Use `duration`(in ms) instead, e.g. `fps=50` == `duration=20` (1000 * 1/50).
    warnings.warn(

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html

Results (52.45s):
      47 passed
```

**Review by pierreguilmin — CHANGES_REQUESTED** [review]
Arf, actually it doesn't work:
```shell
→ pip list | grep imageio
imageio                    2.33.1
→ pytest dynamiqs/plots/plots_wigner.py
Test session starts (platform: darwin, Python 3.9.9, pytest 7.4.4, pytest-sugar 1.0.0)
rootdir: /Users/pierreguilmin/dev/github/dynamiqs
configfile: pytest.ini
plugins: jaxtyping-0.2.25, sugar-1.0.0, typeguard-2.13.3, xdist-3.5.0
collected 47 items

 dynamiqs/plots/plots_wigner.py ✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓       100% ██████████
========================================= warnings summary ==========================================
dynamiqs/plots/plots_wigner.py::line:276,column:1
dynamiqs/plots/plots_wigner.py::line:294,column:1
  /Users/pierreguilmin/.pyenv/versions/3.9.9/envs/dynamiqs/lib/python3.9/site-packages/imageio/plugins/pillow.py:409: DeprecationWarning: The keyword `fps` is no longer supported. Use `duration`(in ms) instead, e.g. `fps=50` == `duration=20` (1000 * 1/50).
    warnings.warn(

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html

Results (52.45s):
      47 passed
```

**Comment by gautierronan** [comment]
This is not the same bug. If you go to older `imageio` versions it raises a `TypeError`, not a warning.

**Comment by gautierronan** [comment]
Actually it was somewhat the same bug. [This](https://github.com/dynamiqs/dynamiqs/pull/520/commits/14008d4585c278f22d5dee9c7c454caa7a289c50) fixes it, and doesn't require a new version of imageio anymore.

**Review by pierreguilmin — APPROVED** [review]

**Pull request merged**
