### PR TITLE
Renamed time arrays to time qarrays

### PR DESCRIPTION
**Pull request by abocquet**
Part of https://linear.app/dynamiqs/issue/DYN-256/qarray-next

- `*TimeArray` -> `*TimeQArray`
- `time_array` -> `time_qarray`
- `time-array` -> `time-qarray`
- `time array` -> `time qarray`

### CODE REVIEW

**Review by pierreguilmin — DISMISSED** [review]
Nice! I've added some missing renamings on top. Could you double-check the new commits? And you can merge if you agree. 😊

**Comment by pierreguilmin** [comment]
I've also added the convention to use `time-qarray` rather than `time qarray` in https://linear.app/dynamiqs/issue/DYN-254/improve-contributingmd.

**Review by pierreguilmin — DISMISSED** [review]

**Review by gautierronan — DISMISSED** [review]
LGTM

**Comment by abocquet** [comment]
Nice catch thanks 🙏

**Review by pierreguilmin — APPROVED** [review]

**Pull request merged**
