### PR TITLE
Refactor how `final_state` and `final_propagator` are saved

### PR DESCRIPTION
**Pull request by dkweiss31**
Supersedes https://github.com/dynamiqs/dynamiqs/pull/682

### CODE REVIEW

**Comment by dkweiss31** [comment]
Not sure why ci is failing, passing locally...

**Comment by gautierronan** [comment]
> Not sure why ci is failing, passing locally...

Seems like its related to latest version of `mkdocstrings-python`. By upgrading I can reproduce locally even on `main`. We need to fix in a separate PR, not sure what's it's due to right now.

**Review by pierreguilmin — APPROVED** [review]
I added minor nits, happy to merge once we've fixed the CI on `main`.

**Comment by gautierronan** [comment]
https://github.com/dynamiqs/dynamiqs/pull/694 fixes the CI, we can merge right after that's done :)

**Comment by dkweiss31** [comment]
Thanks @gautierronan !

**Pull request merged**
